//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisioImportExportVba.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisioImportExportVba.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear before import.
        /// </summary>
        internal static string ClearBeforeImport_Label {
            get {
                return ResourceManager.GetString("ClearBeforeImport_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all VBA code from the target document/stencils.
        /// </summary>
        internal static string ClearBeforeImport_Screentip {
            get {
                return ResourceManager.GetString("ClearBeforeImport_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClearBeforeImport_sm {
            get {
                object obj = ResourceManager.GetObject("ClearBeforeImport_sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all VBA code from the target document/stencils before starting the import (clean import). Ensures that code in the document/stencil does not contain anything except imported code..
        /// </summary>
        internal static string ClearBeforeImport_Supertip {
            get {
                return ResourceManager.GetString("ClearBeforeImport_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExportVBA {
            get {
                object obj = ResourceManager.GetObject("ExportVBA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export VBA.
        /// </summary>
        internal static string ExportVBA_Label {
            get {
                return ResourceManager.GetString("ExportVBA_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export VBA (using last used folder).
        /// </summary>
        internal static string ExportVBA_Screentip {
            get {
                return ResourceManager.GetString("ExportVBA_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExportVBA_sm {
            get {
                object obj = ResourceManager.GetObject("ExportVBA_sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export VBA code from the active document to the last used folder. If there is no &quot;last used folder&quot; then prompts for the folder..
        /// </summary>
        internal static string ExportVBA_Supertip {
            get {
                return ResourceManager.GetString("ExportVBA_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export VBA to a Folder ....
        /// </summary>
        internal static string ExportVBAFolder_Label {
            get {
                return ResourceManager.GetString("ExportVBAFolder_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder and then export VBA code to that folder.
        /// </summary>
        internal static string ExportVBAFolder_Screentip {
            get {
                return ResourceManager.GetString("ExportVBAFolder_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExportVBAFolder_sm {
            get {
                object obj = ResourceManager.GetObject("ExportVBAFolder_sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder and then export VBA code to that folder. Prompts for the target folder and sets is as &quot;last used&quot;.
        /// </summary>
        internal static string ExportVBAFolder_Supertip {
            get {
                return ResourceManager.GetString("ExportVBAFolder_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImportVBA {
            get {
                object obj = ResourceManager.GetObject("ImportVBA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import VBA.
        /// </summary>
        internal static string ImportVBA_Label {
            get {
                return ResourceManager.GetString("ImportVBA_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import VBA (using last used folder).
        /// </summary>
        internal static string ImportVBA_Screentip {
            get {
                return ResourceManager.GetString("ImportVBA_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImportVBA_sm {
            get {
                object obj = ResourceManager.GetObject("ImportVBA_sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import VBA from the last used folder into the current document. If there is no &quot;last used folder&quot; then prompts for the folder..
        /// </summary>
        internal static string ImportVBA_Supertip {
            get {
                return ResourceManager.GetString("ImportVBA_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import VBA from a Folder ....
        /// </summary>
        internal static string ImportVBAFolder_Label {
            get {
                return ResourceManager.GetString("ImportVBAFolder_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder and then import VBAfrom that folder.
        /// </summary>
        internal static string ImportVBAFolder_Screentip {
            get {
                return ResourceManager.GetString("ImportVBAFolder_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImportVBAFolder_sm {
            get {
                object obj = ResourceManager.GetObject("ImportVBAFolder_sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder and then import VBAfrom that folder into current document. Prompts for the target folder and sets is as &quot;last used&quot;.
        /// </summary>
        internal static string ImportVBAFolder_Supertip {
            get {
                return ResourceManager.GetString("ImportVBAFolder_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include stencils.
        /// </summary>
        internal static string IncludeStencils_Label {
            get {
                return ResourceManager.GetString("IncludeStencils_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/export also the code in the docked stencils.
        /// </summary>
        internal static string IncludeStencils_Screentip {
            get {
                return ResourceManager.GetString("IncludeStencils_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IncludeStencils_sm {
            get {
                object obj = ResourceManager.GetObject("IncludeStencils_sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/export also the code in the docked stencils. The code is imported from / exported to to sub-folders in the selected folder.
        /// </summary>
        internal static string IncludeStencils_Supertip {
            get {
                return ResourceManager.GetString("IncludeStencils_Supertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot; onLoad=&quot;OnRibbonLoad&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab idMso=&quot;TabDeveloper&quot;&gt;
        ///        &lt;group id=&quot;Group1&quot; label=&quot;VBA Import Export&quot;&gt;
        ///
        ///          &lt;splitButton id=&quot;ddExportVBA&quot; size=&quot;large&quot; getEnabled=&quot;IsRibbonCommandEnabled&quot;&gt;
        ///            &lt;button id=&quot;ExportVBA&quot; getLabel=&quot;OnGetRibbonLabel&quot; 
        ///                    getScreentip=&quot;OnGetRibbonScreentip&quot; getSupertip=&quot;OnGetRibbonSupertip&quot; onAction=&quot;OnRibb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
    }
}
